name: Run Gitleaks against changed files (caller workflow)
on:
  pull_request:
    branches: [ "master" ]

jobs:
  call-gitleaks-workflow:
    uses: seontechnologies/internal-tools-security/.github/workflows/gitleaks-actions.yml@master
    secrets:
      slackwebhook:  ${{ secrets.CREDENTIAL_LEAK_SLACK_WEBHOOK }}
